### ISSUE TITLE
Build fails: sbt.ResolveException

### ISSUE THREAD

**Issue by nareshvelu96** [alexice/template-scala-parallel-svd-item-similarity#7]
I get the following error when I try to build the engine:

`[INFO] [Engine$] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] 	::          UNRESOLVED DEPENDENCIES         ::
[INFO] [Engine$] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] 	:: org.apache.predictionio#pio-build;0.11.0-incubating: not found
[INFO] [Engine$] [warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[INFO] [Engine$] [warn] 
[INFO] [Engine$] [warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[INFO] [Engine$] [warn] 		org.apache.predictionio:pio-build:0.11.0-incubating (scalaVersion=2.10, sbtVersion=0.13)
[INFO] [Engine$] [warn] 
[INFO] [Engine$] [warn] 	Note: Unresolved dependencies path:
[INFO] [Engine$] [warn] 		org.apache.predictionio:pio-build:0.11.0-incubating (scalaVersion=2.10, sbtVersion=0.13) (/home/nareshvelu96/PredictionIO/template-scala-parallel-svd-item-similarity/project/pio-build.sbt#L1-2)
[INFO] [Engine$] [warn] 		  +- default:template-scala-parallel-svd-item-similarity-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[INFO] [Engine$] sbt.ResolveException: unresolved dependency: org.apache.predictionio#pio-build;0.11.0-incubating: not found
[INFO] [Engine$] 	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
[INFO] [Engine$] 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
[INFO] [Engine$] 	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
[INFO] [Engine$] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[INFO] [Engine$] 	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
[INFO] [Engine$] 	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
[INFO] [Engine$] 	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
[INFO] [Engine$] 	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
[INFO] [Engine$] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
[INFO] [Engine$] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
[INFO] [Engine$] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
[INFO] [Engine$] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[INFO] [Engine$] 	at xsbt.boot.Using$.apply(Using.scala:9)
[INFO] [Engine$] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
[INFO] [Engine$] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
[INFO] [Engine$] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[INFO] [Engine$] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[INFO] [Engine$] 	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
[INFO] [Engine$] 	at sbt.IvySbt.withIvy(Ivy.scala:128)
[INFO] [Engine$] 	at sbt.IvySbt.withIvy(Ivy.scala:125)
[INFO] [Engine$] 	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
[INFO] [Engine$] 	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1481)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1477)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1512)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1510)
[INFO] [Engine$] 	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1515)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1509)
[INFO] [Engine$] 	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
[INFO] [Engine$] 	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1532)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1459)
[INFO] [Engine$] 	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1411)
[INFO] [Engine$] 	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[INFO] [Engine$] 	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
[INFO] [Engine$] 	at sbt.std.Transform$$anon$4.work(System.scala:63)
[INFO] [Engine$] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[INFO] [Engine$] 	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[INFO] [Engine$] 	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[INFO] [Engine$] 	at sbt.Execute.work(Execute.scala:237)
[INFO] [Engine$] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[INFO] [Engine$] 	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[INFO] [Engine$] 	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[INFO] [Engine$] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[INFO] [Engine$] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [Engine$] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[INFO] [Engine$] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] [Engine$] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[INFO] [Engine$] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[INFO] [Engine$] 	at java.lang.Thread.run(Thread.java:748)
[INFO] [Engine$] [error] (*:update) sbt.ResolveException: unresolved dependency: org.apache.predictionio#pio-build;0.11.0-incubating: not found
[INFO] [Engine$] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[ERROR] [Engine$] Return code of build command: /home/nareshvelu96/PredictionIO/PredictionIO-0.11.0-incubating/sbt/sbt  package assemblyPackageDependency is 1. Aborting.
[INFO] [Engine$] Looking for an engine...
[ERROR] [Engine$] No engine found. Your build might have failed. Aborting.
`

Using [this source](https://github.com/PredictionIO/template-scala-parallel-universal-recommendation/issues/53), I realized I have to use org.apache.predictionio rather than io.predictionio, and I had done the same to these files:

> pio-build.sbt
build.sbt
pio.sbt

Even after performing the above changes, the error that is shown above persists. 
**Where else should I make these changes???**

**Comment by abhimanyunagrath** [comment]
@nareshvelu96  I am also facing the same issue. Did you find any solution
